source:      ./_src
destination: ./_staging
plugins:     ./_src/_plugins
layouts:     ./_src/_layouts
timezone:    America/New_York

highlighter: pygments

markdown: kramdown

kramdown:
  input: GFM

sass:
    sass_dir: sass
